version: "3"

services:
  backend:
    build: ./backend
    container_name: backendProduccion
    restart: always
    image: luisbarrera23/backend_practica2_202010223
    environment:
      TZ: America/Guatemala
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /proc:/host/proc:ro
