version: "3"

services:
  backend:
    build: ./backend
    container_name: backendProduccion
    restart: always
    image: luisbarrera23/backend_practica2_202010223
    environment:
      TZ: America/Guatemala
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /proc:/host/proc:ro

  # api:
  #   build: ./api
  #   container_name: apiProduccion
  #   restart: always
  #   image: luisbarrera23/api_practica2_202010223
  #   depends_on:
  #     - db
  #   links: 
  #     - db
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./api/datos:/datos