version: "3"

services:
  db:
    container_name: mysql-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'logs'
      MYSQL_PASSWORD: '1234'
      
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./backend/db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backendProduccion
    restart: always
    image: luisbarrera23/backend_practica2_202010223
    environment:
      TZ: America/Guatemala
    depends_on:
      - db
    links: 
      - db
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /proc:/host/proc:ro

volumes:
  db_data: