version: "3"

services:

  api:
    build: ./api
    container_name: apiProduccion
    restart: always
    image: luisbarrera23/api_practica2_202010223
    depends_on:
      - db
    links: 
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./api/datos:/datos