version: "3"

services:
  db:
    container_name: mysql-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'logs'
      MYSQL_PASSWORD: '1234'
      
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./backend/db_data:/var/lib/mysql

  backend:
    #build: ./backend
    container_name: backendProduccion
    restart: always
    image: luisbarrera23/backend_practica1_202010223
    ports:
      - "5000:5000"
    environment:
      TZ: America/Guatemala
    depends_on:
      - db
    links: 
      - db
    volumes:
      - ./backend/Registros:/registros
  front:
    #build: ./frontend
    container_name: frontendProduccion
    restart: always
    image: luisbarrera23/frontend_practica1_202010223
    ports:
      - "3000:3000"
    depends_on:
      - backend
    links: 
      - backend

  script: 
    #build: ./scripts
    image: luisbarrera23/script_practica1_202010223
    # restart: always
    container_name: scriptProduccion
    environment:
      TZ: America/Guatemala
    volumes:
      - ./backend/Registros:/registros

  
volumes:
  db_data:
  Registros: